web/code/src/forumapp/urls.py
from django.conf.urls import url
from forumapp import views


# I Edited
app_name = "forumapp"
# end I edited

# I Made
urlpatterns = [
    url(r'^$', views.QuestionListView.as_view(), name='question_list'),
    url(r'^question/(?P<pk>\d+)$', views.QuestionDetailView.as_view(), name='question_detail'),
    url(r'^question/new/$', views.QuestionCreateView.as_view(), name='question_new'),
    url(r'^question/(?P<pk>\d+)/edit/$', views.QuestionUpdateView.as_view(), name='question_edit'),
    url(r'^question/(?P<pk>\d+)/remove/$', views.QuestionDeleteView.as_view(), name='question_remove'),

    # Comments :
    url(r'^question/(?P<pk>\d+)/comment/$', views.add_comment_to_question, name='add_comment_to_question'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),

]

web/code/src/my_proj/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

import forumapp.urls    # My Import
import profiles.urls
import accounts.urls
from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),

    # My App
    url(r'forumapp/', include(forumapp.urls, namespace='forumapp')),

    # Google Auth
    url(r'^auth/', include('social_django.urls', namespace='social'))

]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

web/code/src/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),

#     My Added
    url(r'^all/users$', views.all_user_view, name='all_user'),
]

web/code/src/forumapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from profiles.models import BaseProfile
from django.conf import settings
# My Imports

from django.core.urlresolvers import reverse


# class TweetManager(models.Manager):
#
#     def like_toggle(self, user, tweet_obj):
#         if user in tweet_obj.liked.all():
#             is_liked = False
#             tweet_obj.liked.remove(user)
#         else:
#             is_liked = True
#             tweet_obj.liked.add(user)
#         return is_liked


class Question(models.Model):
    # Cannot DO ? ????????????????????????????????
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=1000,null=True)
    # liked = models.ManyToManyField(Profile,blank=True,related_name='liked')
    timestamp = models.DateTimeField(auto_now_add=True)

    # is_published = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('forumapp:question_new')
#        # return reverse('forumapp:question_list')
        #  Changed to redirect the website after
        # submitting the question form to the same form
        # ... so that iframe can be used

    class Meta:
        ordering = ['-timestamp']


class Comment(models.Model):
    question = models.ForeignKey(Question,related_name='comments')
    author_comment = models.ForeignKey(settings.AUTH_USER_MODEL,default=None)
    content = models.CharField(max_length=1000,null=True,blank=False)
    is_valid = models.BooleanField(default=False)
    timestamp_comment = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

    def __unicode__(self):
        return self.content

    class Meta:
        ordering = ['-timestamp_comment']

web/code/src/forumapp/forms.py
from django import forms
from .models import Comment,Question
from django.core import validators


offensive_words = ['fuck','dickhole','dick','sex','fuckyou',
                   'bitch','idiot','anal', 'anus', 'ballsack',
                   'blowjob', 'blow job', 'boner', 'clitoris',
                   'cock', 'cunt', 'dick', 'dildo', 'dyke',
                   'fag', 'fuck', 'jizz', 'labia', 'muff',
                   'nigger', 'nigga', 'penis', 'piss', 'pussy',
                   'scrotum', 'sex', 'shit', 'slut', 'smegma',
                   'spunk', 'twat', 'vagina', 'wank', 'whore']

# Block Offensive Words Validator


def block_offensive_words(value):
    temp = value.split(" ")
    for i in temp:
        if i in offensive_words:
            raise forms.ValidationError("You Cannot post with BAD WORDS")


class QuestionForm(forms.ModelForm):
    content = forms.CharField(max_length=1000, widget=forms.Textarea, validators=[block_offensive_words,])

    class Meta:
        model = Question
        fields = ('title', 'content',)
        widgets = {'vision': forms.Textarea(attrs={'rows': 6,
                                                   'cols': 22,
                                                   'resize': 'none'}),}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        # wid

web/code/src/forumapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
# My Imports :
from forumapp.forms import CommentForm,QuestionForm
from django.views.generic import (TemplateView,ListView
                                 ,DeleteView,DetailView
                                 ,UpdateView,CreateView,)
from forumapp.models import Comment,Question
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import get_object_or_404,redirect
from django.contrib.auth.decorators import login_required


# QUESTION CRUD
class QuestionListView(LoginRequiredMixin,ListView):
    model = Question

    def get_queryset(self):
        return Question.objects.all()


class QuestionDetailView(LoginRequiredMixin,DetailView):
    model = Question


class QuestionCreateView(LoginRequiredMixin,CreateView):
    model = Question
    form_class = QuestionForm
    redirect_field_name = "forumapp/question_form.html"
    #     login_url = '/login/'
    # Newly added

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super(QuestionCreateView, self).form_valid(form)


class QuestionUpdateView(LoginRequiredMixin,UpdateView):
    model = Question
    form_class = QuestionForm
    success_url = reverse_lazy("forumapp:question_list")
    login_url = '/login/'


class QuestionDeleteView(LoginRequiredMixin,DeleteView):
    model = Question
    success_url = reverse_lazy('forumapp:question_list')


# Comments CRUD


@login_required
def add_comment_to_question(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.question = question             # assign the comment to the question which he commented
            comment.author_comment = request.user   # assign each comment to the user who commented it ...
            comment.save()
            return redirect('forumapp:add_comment_to_question', pk=question.pk)
    else:
        form = CommentForm()
    return render(request, 'forumapp/comment_form.html', {'form': form})


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    question_pk = comment.question.pk
    comment.delete()
    return redirect('forumapp:question_detail', pk=question_pk)

web/code/src/forumapp/templates/forumapp/comment_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}


{% block navbar %}

{% endblock %}

{% block container %}
{#    <h1>New comment</h1>#}

    <div class="container col-sm-10" style="padding-left: 20%">
    <form method="POST">
    {% csrf_token %}
    {{form|crispy}}
        <div class="button" style="padding-left: 82%">
    <button type="submit" class="save btn btn-success">Post Comment</button>
            </div>
    </form>
</div>
{#    <script>var editor = new MediumEditor('.editable');</script>#}

{% endblock container %}

{% block footer %}

{% endblock %}

web/code/src/forumapp/templates/forumapp/question_confirm_delete.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}


{% block extrahead %}
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/forum_base1.css" %}">
{% endblock %}


{% block container %}
<br><br><br><br><br><br><br>

{#  <center>  <p>Are you sure you want to delete "{{ object }}"?</p>#}
{#    <input class='btn btn-danger' type="submit" value="Confirm" /></center>#}

<form method="post">{% csrf_token %}
<div class="popup">
  <div class="upper" style="color: red">Are you sure you know what you're doing?</div>
  <div class="stroke"></div>
  <div class="lower">
    <button type="submit"><i class="icon-large icon-ok"></i>yes</button>


{#    <a href="#" onclick="window.history.back(); return false;" class="button cancel-link">No, take me back</a>#}
      <button onclick="window.history.back(); return false" href="#"><i class="icon-large icon-remove"></i>no</button>

  </div>
</div>
  </form>




{% endblock %}
{% block footer %}

{% endblock %}

web/code/src/forumapp/templates/forumapp/question_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}Forum: Detail{% endblock %}


    {% block extrahead %}
{#    <meta http-equiv="refresh" content="1"/>#}
        <link href="https://fonts.googleapis.com/css?family=Arvo" rel="stylesheet">
        <link rel="stylesheet" href="{% static "css/forum_base.css" %}">
{% endblock %}

{% block container %}

      <h1>{{ question.title }}</h1>

        {% if question.timestamp %}

<div class="container profile-body">
  <div class="row">
             <div class="col-sm-12">
            <div class="jumbotron ">
            <h1>{{ question.author.name }}</h1>

        <p>{{ question.content|safe|linebreaksbr }}</p>

                {{ question.timestamp }}
        {% endif %}
</div></div>

</div>

    <div class="row">
        <div class="col-sm-12">
            <div class="jumbotron">
            <iframe src="{% url "forumapp:add_comment_to_question" pk=question.pk %}" height="150px" width="1000" style="border: transparent"></iframe>
            {% for comments in question.comments.all %}
                <div class="jumbotron">
{{ comments.content }}<br>
{{ comments.author_comment }}
                </div>
            {% endfor %}
            </div>
        </div>
    </div>
</div>






{#          {% if user.is_authenticated %}#}
{#          <a class="btn btn-primary" href="{% url 'question_edit' pk=question.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>#}
{#          <a class="btn btn-primary" href="{% url 'question_remove' pk=question.pk %}"><span class="glyphicon glyphicon-remove"></span></a>#}
{#      {% endif %}#}

{#      <hr>#}
{#  <a class="btn btn-primary btn-comment" href="{% url 'add_comment_to_post' pk=post.pk %}">Add comment</a>#}
{#  <div class="container">#}



{% endblock container %}

web/code/src/forumapp/templates/forumapp/question_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

   <!-- To Remove Navbar Just Add The template tag blank in the inherited html-->
{% block navbar %}
{% endblock %}


    {% block extrahead %}
{#    <meta http-equiv="refresh" content="1"/>#}
        <link href="https://fonts.googleapis.com/css?family=Arvo" rel="stylesheet">
        <link rel="stylesheet" href="{% static "css/forum_base.css" %}">
{% endblock %}

{% block container %}
{#    <style>.temporary{background-image: url("/forumapp/static/forum_bag.jpg"); }</style>#}
{% block form %}
    <div class="container form-box">
<center>

    <article>
        <h1>New post</h1>
    <form method="POST" class="post-form">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="save btn btn-primary">Save</button>
    </form>
        </article>

</center>
    </div>
{% endblock %}

    <!-- To Remove Footer Just Add The template tag blank in the inherited html-->
    {% block footer %}
    {% endblock %}
{% endblock %}

web/code/src/forumapp/templates/forumapp/question_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}


{% block title %}{{ block.super }}Forum{% endblock %}

    {% block extrahead %}
{#    <meta http-equiv="refresh" content="1"/>#}
        <link href="https://fonts.googleapis.com/css?family=Arvo" rel="stylesheet">
        <link rel="stylesheet" href="{% static "css/forum_base.css" %}">
{% endblock %}
{% block container %}

{#The Cover Type On the Top has the form#}

<br><br><br>

    <!-- For the click and open a collapsing bar effect-->
<center>
{#<div class="btn-group">#}
{#  <button style="width: 100%" type="button" class="btn btn-danger">Have A Question ?? </button>#}
  <button style="width: 50%" type="button" class="btn btn-primary" data-toggle="collapse" data-target="#demo">
   Have A Question ??  <span class="glyphicon glyphicon-arrow-down"></span>
  </button>
{#</div>#}
</center>

<div id="demo" class="collapse">    <!-- For the click and open a collapsing bar effect-->
<!-- Form -->
<div class="container profile-head">
  <div class="row">
    <div class="col-sm-10">
        <!-- Functionality added in Iframe -->
        <center><iframe src="{% url "forumapp:question_new" %}" style="border:2px solid grey;text-align: center;" width="1125" height="550" ></iframe></center>
    </div>
  </div>
</div>
</div>      <!-- End of div  :       For the click and opening : a collapsing bar effect-->

{#</div>#}

<hr style="border-color: black;" class="col-sm-12">
{#<div class="">#}
<div class="container profile-body new-decided">
  <div class="row">
    <div class="col-sm-11">

    {% for question in question_list %}
        <div class="jumbotron" style="border: groove;">
{#Question #}

            <!-- Profile Image -->

   <div class="row" style="margin-left: -50px;margin-top: 0px">
      <div class="row2">
          <!-- Taking User To The profile page of the author of the post-->
       <div class="col-md-10">
        <a href="{% url "profiles:show" slug=question.author.profile.slug %}"><div class="col-md-1"> <img title="profile picture" class="img-circle img-responsive" src="{% thumbnail question.author.profile.picture|default:'default_profile.png' 60x60 crop %}">
               </div>
               </a>


{#          <strong style="color: #de0c00">Q-</strong>#}

{#        <div class="s1"></div>#}
                <p><h2>
                <a href="{% url 'forumapp:question_detail' pk=question.pk %}">{{ question.author.name }}</a></h2>
                <a href="{% url 'forumapp:question_detail' pk=question.pk %}">{{ question.author.email }}</a></p>
</div>
          <!-- Added Delete And Edit Functionality to the Questions-->
          {% if question.author.profile.user == user %}
          <a class="btn btn-success" href="{% url 'forumapp:question_edit' pk=question.pk %}">Edit?</a>
          <a class="btn btn-danger" href="{% url 'forumapp:question_remove' pk=question.pk %}">Delete?</a>
{% endif %}


      </div>
  </div>
{#            <a href="{% url 'forumapp:question_detail' pk=question.pk %}"><p><h2>{{ question.title }}</h2></a></p>#}

{# having the read more button#}
            <h3>{{ question.content }}</h3>
  <p class="read-more"><a href="{% url "forumapp:question_detail" pk=question.pk %}" class="button">Answers</a></p>


            <div class="date">
                Published on__{{ question.timestamp|date }}  -
                {{ question.timestamp|timesince}} ago - {{ question.timestamp|time}}
                <!--Name--><br>
                By :  {{ question.author.name.capitalize }}
            </div>

{#            <a href="{% url 'question_detail' pk=post.pk %}">Comments: {{ post.approve_comments.count }}</a>#}
        </div>
    {% endfor %}
    </div>
  </div>
</div>


{% endblock container %}